package entity;
// Generated 15 janv. 2013 14:56:54 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Categorie generated by hbm2java
 */
public class Categorie  implements java.io.Serializable {


     private Integer idCat;
     private String nomCat;
     private Set produitses = new HashSet(0);

    public Categorie() {
    }

    public Categorie(String nomCat, Set produitses) {
       this.nomCat = nomCat;
       this.produitses = produitses;
    }
   
    public Integer getIdCat() {
        return this.idCat;
    }
    
    public void setIdCat(Integer idCat) {
        this.idCat = idCat;
    }
    public String getNomCat() {
        return this.nomCat;
    }
    
    public void setNomCat(String nomCat) {
        this.nomCat = nomCat;
    }
    public Set getProduitses() {
        return this.produitses;
    }
    
    public void setProduitses(Set produitses) {
        this.produitses = produitses;
    }




}


