package entity;
// Generated 15 janv. 2013 14:56:54 by Hibernate Tools 3.2.1.GA



/**
 * Commentaires generated by hbm2java
 */
public class Commentaires  implements java.io.Serializable {


     private Integer idCommentaire;
     private Produits produits;
     private String commentaire;
     private String etat;

    public Commentaires() {
    }

	
    public Commentaires(Produits produits) {
        this.produits = produits;
    }
    public Commentaires(Produits produits, String commentaire, String etat) {
       this.produits = produits;
       this.commentaire = commentaire;
       this.etat = etat;
    }
   
    public Integer getIdCommentaire() {
        return this.idCommentaire;
    }
    
    public void setIdCommentaire(Integer idCommentaire) {
        this.idCommentaire = idCommentaire;
    }
    public Produits getProduits() {
        return this.produits;
    }
    
    public void setProduits(Produits produits) {
        this.produits = produits;
    }
    public String getCommentaire() {
        return this.commentaire;
    }
    
    public void setCommentaire(String commentaire) {
        this.commentaire = commentaire;
    }
    public String getEtat() {
        return this.etat;
    }
    
    public void setEtat(String etat) {
        this.etat = etat;
    }




}


