package entity;
// Generated 15 janv. 2013 14:56:54 by Hibernate Tools 3.2.1.GA



/**
 * LigneCommande generated by hbm2java
 */
public class LigneCommande  implements java.io.Serializable {


     private LigneCommandeId id;
     private Panier panier;
     private Produits produits;
     private Double totalCmd;
     private Integer quantite;

    public LigneCommande() {
    }

	
    public LigneCommande(LigneCommandeId id, Panier panier, Produits produits) {
        this.id = id;
        this.panier = panier;
        this.produits = produits;
    }
    public LigneCommande(LigneCommandeId id, Panier panier, Produits produits, Double totalCmd, Integer quantite) {
       this.id = id;
       this.panier = panier;
       this.produits = produits;
       this.totalCmd = totalCmd;
       this.quantite = quantite;
    }
   
    public LigneCommandeId getId() {
        return this.id;
    }
    
    public void setId(LigneCommandeId id) {
        this.id = id;
    }
    public Panier getPanier() {
        return this.panier;
    }
    
    public void setPanier(Panier panier) {
        this.panier = panier;
    }
    public Produits getProduits() {
        return this.produits;
    }
    
    public void setProduits(Produits produits) {
        this.produits = produits;
    }
    public Double getTotalCmd() {
        return this.totalCmd;
    }
    
    public void setTotalCmd(Double totalCmd) {
        this.totalCmd = totalCmd;
    }
    public Integer getQuantite() {
        return this.quantite;
    }
    
    public void setQuantite(Integer quantite) {
        this.quantite = quantite;
    }




}


