package entity;
// Generated 15 janv. 2013 14:56:54 by Hibernate Tools 3.2.1.GA



/**
 * LigneCommandeId generated by hbm2java
 */
public class LigneCommandeId  implements java.io.Serializable {


     private int idPanier;
     private int idProduit;

    public LigneCommandeId() {
    }

    public LigneCommandeId(int idPanier, int idProduit) {
       this.idPanier = idPanier;
       this.idProduit = idProduit;
    }
   
    public int getIdPanier() {
        return this.idPanier;
    }
    
    public void setIdPanier(int idPanier) {
        this.idPanier = idPanier;
    }
    public int getIdProduit() {
        return this.idProduit;
    }
    
    public void setIdProduit(int idProduit) {
        this.idProduit = idProduit;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LigneCommandeId) ) return false;
		 LigneCommandeId castOther = ( LigneCommandeId ) other; 
         
		 return (this.getIdPanier()==castOther.getIdPanier())
 && (this.getIdProduit()==castOther.getIdProduit());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPanier();
         result = 37 * result + this.getIdProduit();
         return result;
   }   


}


