package entity;
// Generated 15 janv. 2013 14:56:54 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Notations generated by hbm2java
 */
public class Notations  implements java.io.Serializable {


     private Integer idNotation;
     private Produits produits;
     private Integer critere;
     private Integer note;
     private Set critereses = new HashSet(0);

    public Notations() {
    }

	
    public Notations(Produits produits) {
        this.produits = produits;
    }
    public Notations(Produits produits, Integer critere, Integer note, Set critereses) {
       this.produits = produits;
       this.critere = critere;
       this.note = note;
       this.critereses = critereses;
    }
   
    public Integer getIdNotation() {
        return this.idNotation;
    }
    
    public void setIdNotation(Integer idNotation) {
        this.idNotation = idNotation;
    }
    public Produits getProduits() {
        return this.produits;
    }
    
    public void setProduits(Produits produits) {
        this.produits = produits;
    }
    public Integer getCritere() {
        return this.critere;
    }
    
    public void setCritere(Integer critere) {
        this.critere = critere;
    }
    public Integer getNote() {
        return this.note;
    }
    
    public void setNote(Integer note) {
        this.note = note;
    }
    public Set getCritereses() {
        return this.critereses;
    }
    
    public void setCritereses(Set critereses) {
        this.critereses = critereses;
    }




}


