package entity;
// Generated 15 janv. 2013 14:56:54 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Panier generated by hbm2java
 */
public class Panier  implements java.io.Serializable {


     private Integer idPanier;
     private Personnes personnes;
     private Float prixCmd;
     private Date date;
     private Set personneses = new HashSet(0);
     private Set ligneCommandes = new HashSet(0);

    public Panier() {
    }

    public Panier(Personnes personnes, Float prixCmd, Date date, Set personneses, Set ligneCommandes) {
       this.personnes = personnes;
       this.prixCmd = prixCmd;
       this.date = date;
       this.personneses = personneses;
       this.ligneCommandes = ligneCommandes;
    }
   
    public Integer getIdPanier() {
        return this.idPanier;
    }
    
    public void setIdPanier(Integer idPanier) {
        this.idPanier = idPanier;
    }
    public Personnes getPersonnes() {
        return this.personnes;
    }
    
    public void setPersonnes(Personnes personnes) {
        this.personnes = personnes;
    }
    public Float getPrixCmd() {
        return this.prixCmd;
    }
    
    public void setPrixCmd(Float prixCmd) {
        this.prixCmd = prixCmd;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Set getPersonneses() {
        return this.personneses;
    }
    
    public void setPersonneses(Set personneses) {
        this.personneses = personneses;
    }
    public Set getLigneCommandes() {
        return this.ligneCommandes;
    }
    
    public void setLigneCommandes(Set ligneCommandes) {
        this.ligneCommandes = ligneCommandes;
    }




}


