package entity;
// Generated 15 janv. 2013 14:56:54 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Personnes generated by hbm2java
 */
public class Personnes  implements java.io.Serializable {


     private Integer idPersonne;
     private Panier panier;
     private String nom;
     private String prenom;
     private String adresse;
     private String email;
     private String login;
     private String mdp;
     private String profil;
     private Set paniers = new HashSet(0);

    public Personnes() {
    }

    public Personnes(Panier panier, String nom, String prenom, String adresse, String email, String login, String mdp, String profil, Set paniers) {
       this.panier = panier;
       this.nom = nom;
       this.prenom = prenom;
       this.adresse = adresse;
       this.email = email;
       this.login = login;
       this.mdp = mdp;
       this.profil = profil;
       this.paniers = paniers;
    }
   
    public Integer getIdPersonne() {
        return this.idPersonne;
    }
    
    public void setIdPersonne(Integer idPersonne) {
        this.idPersonne = idPersonne;
    }
    public Panier getPanier() {
        return this.panier;
    }
    
    public void setPanier(Panier panier) {
        this.panier = panier;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getMdp() {
        return this.mdp;
    }
    
    public void setMdp(String mdp) {
        this.mdp = mdp;
    }
    public String getProfil() {
        return this.profil;
    }
    
    public void setProfil(String profil) {
        this.profil = profil;
    }
    public Set getPaniers() {
        return this.paniers;
    }
    
    public void setPaniers(Set paniers) {
        this.paniers = paniers;
    }




}


